again and again

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,41 +1,74 @@
 name: Main workflow
-
 on: push
-
-env:
-  github_username: salar778
-  github_password: ${{ secrets.GITHUB_TOKEN }}
+env: # Set the secret as an input
+  github_username: ${{ github.actor }}
+  github_password: ${{ secrets.GITHUB_TOKEN }} # Must be made available to the workflow
   GIT_COMMIT: ${{ github.sha }}
 
 jobs:
   Build:
     runs-on: ubuntu-latest
     container: gradle:6-jdk11
-
     steps:
       - name: Clone down repository
-        uses: actions/checkout@v4
-
+        uses: actions/checkout@v4       
       - name: Build application
         run: ci/build-app.sh
-
       - name: Test
         run: ci/unit-test-app.sh
-
       - name: Upload repo
         uses: actions/upload-artifact@v4
-        with:
+        with: 
           name: code
           path: .
           include-hidden-files: true
 
+  Linting:
+    runs-on: ubuntu-latest
+    needs: [Build]
+    steps:
+      - name: Download code
+        uses: actions/download-artifact@v4
+        with:
+          name: code
+          path: .
+      - name: run linting
+        uses: super-linter/super-linter/slim@v7 
+        env:
+          DEFAULT_BRANCH: main
+          # To report GitHub Actions status checks
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          DISABLE_ERRORS: true
+
   Docker-image:
     runs-on: ubuntu-latest
     needs: [Build]
-
     permissions:
       packages: write
-      contents: read
+    steps:
+    - name: Download code
+      uses: actions/download-artifact@v4
+      with:
+        name: code
+        path: .
+    - name: Validate Docker username is all lowercase
+      id: validate_lower
+      run: |
+        if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
+          echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
+          exit 1
+        else
+          echo "Docker username format is valid."
+        fi
+      shell: bash
+    - name: build docker
+      run: bash ci/build-docker.sh
+    - name: push docker
+      run: bash ci/push-docker.sh
+  
+  Component-test:
+    runs-on: ubuntu-latest
+    needs: Docker-image
 
     steps:
       - name: Download code
@@ -44,8 +77,20 @@ jobs:
           name: code
           path: .
 
-      - name: Build docker
-        run: bash ci/build-docker.sh
+      - name: Execute component test
+        run: bash ci/component-test.sh
 
-      - name: Push docker
-        run: bash ci/push-docker.sh
+
+  Performance-test:
+    runs-on: ubuntu-latest
+    needs: Docker-image
+
+    steps:
+      - name: Download code
+        uses: actions/download-artifact@v4
+        with:
+          name: code
+          path: .
+
+      - name: Execute performance test
+        run: bash ci/performance-test.sh    #Salar
